Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Metrics/LineLength:
  Max: 100

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false
